---
- name: enable Serial port hardware
  shell: "raspi-config nonint do_serial 2"

- name: enable services
  systemd:
    state: started
    enabled: yes
    name: "{{ item }}"
  become: yes
  loop:
    - nfc_scanner.service
    - mopidy.service
