---
- name: install python3
  apt: 
    name: python3
    state: present

- name: install python3-pip
  apt: 
    name: python3-pip
    state: present

- name: install git
  apt: 
    name: git
    state: present

