---
- name: set remote conf folder variables
  set_fact: 
    remote_mopidy_conf_folder: "/home/{{ ansible_user }}/.config/mopidy/"
    remote_project_app_folder: "/home/{{ ansible_user }}/apps/nfc-scanner/"

- name: create dir 
  file:
    path: "{{ remote_project_app_folder }}/lib/pn532"
    state: directory
    mode: '0755'

- name: copy NFC Scanner configuration files
  copy:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: "{{ remote_project_app_folder }}/{{ item }}"
  loop:
    - requirements.txt
    - mopidy_folders.json
    - mopidy_stations.json
    - mopidy_youtube_playlists.json
    - main.py
    - lib/logger.py
    - lib/mopidy_nfc_scanner.py
    - lib/mopidy_http_service.py
    - lib/pn532/i2c.py
    - lib/pn532/spi.py
    - lib/pn532/uart.py
    - lib/pn532/pn532.py

- name: install project requirements
  pip: 
    requirements: "{{ remote_project_app_folder }}/requirements.txt"
    extra_args: --user

- name: push templates for services
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  become: yes
  loop:
    - mopidy.service
    - nfc_scanner.service

  
